### PR TITLE
Revert 2 revert 1 develop

### PR DESCRIPTION
**Pull request by thonglhuet**

### CODE REVIEW

**Comment by thonglhuet** [comment]
ready

**Comment by hungnh103** [comment]
commented

**Review by hungnh103 — COMMENTED** [review]
gdsgf

**Comment by hungnh103** [comment]
fasfasf

**Comment by hungnh103** [comment]
commented

**Comment by thonglhuet** [comment]
commented

**Comment by thonglhuet** [comment]
commented

**Comment by hungnh103** [comment]
commented

**Comment by thonglhuet** [comment]
ready

**Comment by thonglhuet** [comment]
commented

**Comment by thonglhuet** [comment]
ready

**Comment by thonglhuet** [comment]
commented
(cap)

**Comment by thonglhuet** [comment]
ready
:gach:

**Comment by thonglhuet** [comment]
reviewing

**Pull request merged**
